# Generated by Django 3.2.12 on 2023-05-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(default='sport', on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(default='any tags', to='api.Tags', verbose_name='tags'),
        ),
    ]
